---
title: "Summary tables"
author: "Shu Wei"
date: "3/15/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(kableExtra)
```

# Resultados (DLNM lineal)

```{r}
metrica.canton.in <- read.csv("results/metricas_Canton_INLA_in.csv")
metrica.canton.out <- read.csv("results/metricas_Canton_INLA_out.csv")

metrica.DTW6.in <- read.csv("results/metricas_cluster_DTW6_INLA_in.csv")
metrica.DTW6.out <- read.csv("results/metricas_cluster_DTW6_INLA_out.csv")

metrica.WL6.in <- read.csv("results/metricas_cluster_wl6_INLA_in.csv")
metrica.WL6.out <- read.csv("results/metricas_cluster_wl6_INLA_out.csv")

tabla.in <- metrica.canton.in %>% left_join(metrica.DTW6.in,by="Canton") %>% 
      left_join(metrica.DTW6.in,by="Canton")

tabla.out <- metrica.canton.out %>% left_join(metrica.DTW6.out,by="Canton") %>% 
  left_join(metrica.DTW6.out,by="Canton")


```

```{r}
options(scipen=999)
tabla.in %>% kbl(digits=2)%>%
  kable_minimal() %>%
  kable_paper(full_width = F) %>%
  add_header_above(c(" " = 1, "Model6.1" = 2, 
                              "Model6.2" = 2,
                              "Model6.3" = 2))
```

```{r}
tabla.out %>% kbl(digits=2)%>%
  kable_minimal() %>%
  kable_paper(full_width = F) %>%
  add_header_above(c(" " = 1, "Model6.1" = 2, 
                              "Model6.2" = 2,
                              "Model6.3" = 2))
```


# Resultados (DLNM no lineal)

```{r}
metrica.canton.nolineal.in <- read.csv("results/metricas_Canton_INLA_nolineal_in.csv")
metrica.canton.nolineal.out <- read.csv("results/metricas_Canton_INLA_nolineal_out.csv")

metrica.DTW6.nolineal.in <- read.csv("results/metricas_cluster_DTW6_INLA_nolineal_in.csv")
metrica.DTW6.nolineal.out <- read.csv("results/metricas_cluster_DTW6_INLA_nolineal_out.csv")

metrica.WL6.nolineal.in <- read.csv("results/metricas_cluster_wl6_INLA_nolineal_in.csv")
metrica.WL6.nolineal.out <- read.csv("results/metricas_cluster_wl6_INLA_nolineal_out.csv")

tabla.nolineal.in <- metrica.canton.nolineal.in %>% left_join(metrica.DTW6.nolineal.in,by="Canton") %>% 
      left_join(metrica.DTW6.nolineal.in,by="Canton")

tabla.nolineal.out <- metrica.canton.nolineal.out %>% left_join(metrica.DTW6.nolineal.out,by="Canton") %>% 
  left_join(metrica.DTW6.nolineal.out,by="Canton")


```

```{r}
options(scipen=999)
tabla.nolineal.in %>% kbl(digits=2)%>%
  kable_minimal() %>%
  kable_paper(full_width = F) %>%
  add_header_above(c(" " = 1, "Model6.1" = 2, 
                              "Model6.2" = 2,
                              "Model6.3" = 2))
```

```{r}
tabla.nolineal.out %>% kbl(digits=2)%>%
  kable_minimal() %>%
  kable_paper(full_width = F) %>%
  add_header_above(c(" " = 1, "Model6.1" = 2, 
                              "Model6.2" = 2,
                              "Model6.3" = 2))
```



